# Generated by Django 4.0.4 on 2022-05-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='locales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantLocales', models.IntegerField()),
                ('nomLocales', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='patioComidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantLocales', models.IntegerField()),
                ('nomLocales', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='promos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechas', models.DurationField()),
            ],
        ),
    ]
