# Generated by Django 4.0.4 on 2022-05-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='cine',
            options={'verbose_name': 'Cine', 'verbose_name_plural': 'Cines'},
        ),
        migrations.AlterModelOptions(
            name='locales',
            options={'verbose_name': 'Local', 'verbose_name_plural': 'Locales'},
        ),
        migrations.AlterModelOptions(
            name='promos',
            options={'verbose_name': 'Promo', 'verbose_name_plural': 'Promos'},
        ),
        migrations.AddField(
            model_name='cine',
            name='cantPelis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cine',
            name='peliculas',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='promos',
            name='precios',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promos',
            name='promociones',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
