# Generated by Django 4.0.4 on 2022-05-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0003_alter_locales_cantlocales_alter_locales_nomlocales_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuario',
            new_name='registro',
        ),
        migrations.AlterModelOptions(
            name='patiocomidas',
            options={'verbose_name': 'Patio de Comidas', 'verbose_name_plural': 'Patio de Comidas'},
        ),
    ]
