# Generated by Django 4.0.4 on 2022-05-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0004_rename_usuario_registro_alter_patiocomidas_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
