# Generated by Django 4.0.4 on 2022-05-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0005_registro_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro',
            options={'verbose_name': 'Registro', 'verbose_name_plural': 'Registros'},
        ),
    ]
