# Generated by Django 4.0.4 on 2022-05-03 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0006_alter_registro_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registro',
            new_name='Usuarios',
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='nombre',
            new_name='usuario',
        ),
    ]
