# Generated by Django 4.0.4 on 2022-05-26 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0007_rename_registro_usuarios_alter_usuarios_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='usuario',
            new_name='nombre',
        ),
    ]
