# Generated by Django 4.0.4 on 2022-05-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0008_rename_usuario_usuarios_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPromos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('edad', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Promo',
                'verbose_name_plural': 'Promos',
            },
        ),
        migrations.DeleteModel(
            name='promos',
        ),
    ]
