# Generated by Django 4.0.4 on 2022-05-26 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0009_registropromos_delete_promos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registropromos',
            options={'verbose_name': 'Usuario_Promo', 'verbose_name_plural': 'Usuarios_Promos'},
        ),
    ]
